#!/bin/sh

WORKING_DIR=`pwd`
echo "Start install dotfiles..."

echo "installing zsh dotfiles"
ln -sf $WORKING_DIR/zsh/zshrc ~/.zshrc
ln -sf $WORKING_DIR/zsh/zsh ~/.zsh

echo "installing vim dotfiles"
ln -sf $WORKING_DIR/vim/vimrc ~/.vimrc
ln -sf $WORKING_DIR/vim/vim ~/.vim

echo "installing tmux dotfiles"
ln -sf $WORKING_DIR/tmux/tmux.conf ~/.tmux.conf

echo "installing maid dotfiles"
ln -sf $WORKING_DIR/maid ~/.maid
